services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresqldata
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017    
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auctionsvc:
      image: mbradley672/auction-service:latest
      build:
        context: .
        dockerfile: src/AuctionService/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80;https://+:443;http://+:7777
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Auctions
        - IdentityService__Uri=http://identitysvc
        - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - Kestrel__Certificates__Default__Password=Pass123$
        - Kestrel__Endpoints__Grpc__Porotcols=Http2
        - Kestrel__Endpoints__Grpc__Url=http://*:7777
        - Kestrel__Endpoints__WebApi__Url=http://*:80
        - Kestrel__Endpoints__WebApi__Porotcols=Http1
      volumes:
      - "~/.aspnet/https:/https/"
      ports:
        - 7001:80
        - 7011:443
        - 7777:7777
      depends_on: 
        - postgres
        - rabbitmq
  searchsvc:
    image: mbradley672/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - RabbitMq__Host=rabbitmq
      - AuctionServiceUrl=http://auctionsvc
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb/?authMechanism=SCRAM-SHA-256
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=Pass123$
    volumes:
      - "~/.aspnet/https:/https/"
    ports:
      - 7002:80
      - 7012:443
    depends_on:
      - mongodb
      - rabbitmq
  identitysvc:
    image: mbradley672/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Identity
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=Pass123$
    volumes:
      - "~/.aspnet/https:/https/"
    ports:
      - 5000:80
      - 5010:443
    depends_on:
      - postgres
  gatewaysvc:
    image: mbradley672/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=Pass123$
    volumes:
      - "~/.aspnet/https:/https/"
    ports:
      - 6001:80
      - 6011:443
  bidsvc:
    image: mbradley672/bid-service:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=mongodb://root:mongopw@mongodb/?authMechanism=SCRAM-SHA-256
      - IdentityService__Uri=http://identitysvc
      - GrpcAuction=http://auctionsvc:7777
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=Pass123$
    volumes:
      - "~/.aspnet/https:/https/"
    ports:
      - 7003:80
      - 7013:443
    depends_on:
      - mongodb
      - rabbitmq
  notifysvc:
    image: mbradley672/notify-service:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - RabbitMq__Host=rabbitmq
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=Pass123$
    volumes:
      - "~/.aspnet/https:/https/"
    ports:
      - 7004:80 
    depends_on: 
      - rabbitmq

volumes:
  pgdata:    
  mongodata:
    